USE BKRestrauntdb;
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100) UNIQUE,
    VIP BOOLEAN DEFAULT FALSE,
    credits INT DEFAULT 0
);